### ISSUE TITLE
Unable to get to configuration

### ISSUE THREAD

**Issue by liamstears** [smartgauges/canbox#2]
So I've been playing with this some time and finally got my ST-Link to work and have flashed [volvo_od2.bin](https://github.com/smartgauges/canbox/blob/main/volvo_od2.bin) to my canbus box. I have verified it has flashed. However the box does not function in the car and I have tried to connect TX/RX to pc using putty but I am just getting some scrambled messages which stop after a few lines at baud 9600. How can I troubleshoot? Is baud rate for putty 9600? Hope you can help point me in the right direction...

**Comment by smartgauges** [comment]
Hello, i have added information on configuring the adapter on the main page
https://github.com/smartgauges/canbox

Since the adapter supports several car models and protocols, the adapter must first be configured for a specific car. To configure, the adapter must be connected to the Rx and TX lines at 38400 speed using any terminal program (putty, hyperterminal, minicom ...)
Changing the configuration of the adapter is possible in debug mode. Switching to debug mode occurs when you press the corresponding keys on the keyboard:
- OOOOOOOOOOOOO switch to debug mode (must send at least 10 O characters in 1 second)
- o switch to normal mode
- b selection of the emulated protocol from the list Raise VW(PQ), Raise VW(MQB), Oudi BMW(Nbt Evo, HiWorld VW(MQB)
- c selection of a car from the list FL2 2007MY, FL2 2013MY, XC90 2007MY
- I increase the backlight level threshold
- i decrease the backlight level threshold
- D increase camera turn off delay
- d decrease camera turn off delay
- m selection of active CAN message
- s save configuration
